### PR TITLE
Support OIDC compliant auth provider

### PR DESCRIPTION
**Pull request by jonnyshaw89**
This PR uses the new `eq-ecs-deploy` version that supports auth. However in this PR it is currently disabled and still uses firebase

This PR also runs UI and API on the same domain. which has a performance improvement in not needing to perform CORS requests before every API call

### CODE REVIEW

**Review by tgandrews — APPROVED** [review]
Works as expected with no `OPTIONS` call 👍

**Review by samiwel — APPROVED** [review]
Tested and seems to behave as expected.

**Comment by tgandrews** [comment]
@jonnyshaw89 what is this waiting on now?

**Comment by jonnyshaw89** [comment]
@tgandrews nothing now. I just had to set the `ref=` to the new release tag

**Pull request merged**
